# Generated by Django 5.1.7 on 2025-03-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_models',
            new_name='student',
        ),
    ]
